Fix initial starting behavior in debian

diff --git a/pkg/deb/postinst b/pkg/deb/postinst
--- a/pkg/deb/postinst
+++ b/pkg/deb/postinst
@@ -26,5 +26,49 @@ configure)
     ;;
 esac
 
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    # This will only remove masks created by d-s-h on package removal.
+    deb-systemd-helper unmask ntpd-rs.service >/dev/null || true
+
+    # was-enabled defaults to true, so new installations run enable.
+    if deb-systemd-helper --quiet was-enabled ntpd-rs.service; then
+        # Enables the unit on first installation, creates new
+        # symlinks on upgrades if the unit file has changed.
+        deb-systemd-helper enable ntpd-rs.service >/dev/null || true
+    else
+        # Update the statefile to add new symlinks (if any), which need to be
+        # cleaned up on purge. Also remove old symlinks.
+        deb-systemd-helper update-state ntpd-rs.service >/dev/null || true
+    fi
+fi
+
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    if deb-systemd-helper debian-installed ntpd-rs-metrics.service; then
+        # This will only remove masks created by d-s-h on package removal.
+        deb-systemd-helper unmask ntpd-rs-metrics.service >/dev/null || true
+
+        if deb-systemd-helper --quiet was-enabled ntpd-rs-metrics.service; then
+            # Create new symlinks, if any.
+            deb-systemd-helper enable ntpd-rs-metrics.service >/dev/null || true
+        fi
+    fi
+
+    # Update the statefile to add new symlinks (if any), which need to be cleaned
+    # up on purge. Also remove old symlinks.
+    deb-systemd-helper update-state ntpd-rs-metrics.service >/dev/null || true
+fi
+
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action ntpd-rs.service >/dev/null || true
+	fi
+fi
+
 
 #DEBHELPER#
